### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by offreal** [Sreyas-Sreelal/tgconnector#1]
Hey. I had a server crash with online. I suspect your plugin, because Crashdetect did not want to show the exact reason. (crashdetect 4.19 version, try update, to 4.19.4, mb show reason)

Showed only this:
[31/01/2019 15:20:28] [debug] Server crashed due to an unknown error

The last thing I did, I sent a message to the telegraph group.
Messages catch through: 
public OnTGMessage(TGBot:bot, TGUser:fromid, TGMessage:messageid) 

Help fix it, tk. Before this, the server with online 100 worked stably.
Ready to help if you need it.

**Comment by Sreyas-Sreelal** [comment]
Can you provide me a minimal code to reproduce this crash?

**Comment by Sreyas-Sreelal** [comment]
Haven't heard from you in a while.I'm assuming that the crash wasn't from this plugin and therefore closing this issue.Re open it if you feel otherwise.
