### ISSUE TITLE
PLUGIN LOAD FAILED

### ISSUE THREAD

**Issue by v1mper228** [Sreyas-Sreelal/tgconnector#12]
Loading plugin: tgconnector.so
[18:06:25]   Failed (libssl.so.1.1: cannot open shared object file: No such file or directory)
why?
host maze-host

**Comment by Sreyas-Sreelal** [comment]
Install openssl in your server

**Comment by ajas01862** [comment]
> Install openssl in your server

How to install it on samp ?
