### ISSUE TITLE
Issue w/ newest version (1.1.1)

### ISSUE THREAD

**Issue by Chaprnks** [Sreyas-Sreelal/tgconnector#15]
compiled without -d3
`[TgConnector] [info]: Warning plugin and include version doesnot match : Include 111 Plugin 110`

compiled with -d3
`[TgConnector] [error]: Failed to retrive include version Reason:NotFound`

**Comment by Sreyas-Sreelal** [comment]
Thank you. I forgot to bump the version number in plugin, I re released the plugin.
