### ISSUE TITLE
Support proxy.

### ISSUE THREAD

**Issue by continue98** [Sreyas-Sreelal/tgconnector#2]
Hi .If possible, you need to add settings for the proxy. (in some countries, telegram is blocked (for example: Russia)

**Comment by Sreyas-Sreelal** [comment]
Sorry for late reply and yes it's possible,I'll add this feature soon enough!

**Comment by continue98** [comment]
I could try to do PR, but I don't know Rust. If it were C++, I would not write issues, but make PR

**Comment by continue98** [comment]
@Sreyas-Sreelal Add an example of using a proxy to readme.

In addition, in native (proxy settings), the parameter for this setting must be specified as const

**Comment by Sreyas-Sreelal** [comment]
It's not done yet,i didn't merge it to master.
Well for an example currently you just pass proxy server' URL as argument
