### ISSUE TITLE
encoding message text to utf-8

### ISSUE THREAD

**Issue by continue98** [Sreyas-Sreelal/tgconnector#4]
Hi, SA-MP doesn't support utf-8, so I suggest adding a built-in decoder to utf-8

P.S: telegram can only accept utf-8

**Comment by continue98** [comment]
I suggest using iconv (binding for rust: https://github.com/andelf/rust-iconv)

**Comment by ExileFox** [comment]
i believe it does if you save the pwn file as UTF-8 encoded
