### ISSUE TITLE
[TgConnector] [error]: Failed to retrive include version Reason:NotFound

### ISSUE THREAD

**Issue by Ryder17z** [Sreyas-Sreelal/tgconnector#5]
I can't see where this issue stems from.

Using latest release and the current include.

**Comment by Sreyas-Sreelal** [comment]
I can't reproduce this.. The error basically says it can't find the public variable `_tgconnector_version`

**Comment by ExileFox** [comment]
i wanted to run this as a filterscript but now have changed it to a gamemode and it works

**Comment by Sreyas-Sreelal** [comment]
Can you try the latest version ? The error doesn't popup for me whether it's filterscript or gamemode
