### ISSUE TITLE
OnTGMessage(TGBot:bot,TGUser:fromid[],TGMessage:messageid) doesn't work

### ISSUE THREAD

**Issue by FelixKot** [Sreyas-Sreelal/tgconnector#8]
Hello! 
I'm trying to call OnTGMessage. But it doesn't work. My code doesn't output "yes".
`public OnTGMessage(TGBot:bot,TGUser:fromid[],TGMessage:messageid) {

	print("yes");
	if(g_bot != bot){
		return 1;
	}

	new
		message[50],
		username[24],
		chatname[56],
		server_msg[128];

	TG_CacheGetMessage(message);
	TG_CacheGetUserName(username);
	TG_CacheGetChatName(chatname);

	format(server_msg,128,"[%s] %s(%s): %s",chatname,username,_:fromid,message);
	print(server_msg);
	SendClientMessageToAll(-1,server_msg);

	return 1;
}`

This is not accompanied by any errors.

**Comment by Sreyas-Sreelal** [comment]
How are you testing this? This callback will only get called when a group/super group or private message is sent. 
If you're sending message in a channel you should use `OnTGChannelPost(TGBot:bot,TGMessage:postid)` callback. 
And in either of the case the bot must be a member of these type of conversations, like a bot can read only message from groups which it's a member of.

**Comment by FelixKot** [comment]
The bot is a member and administrator of a private group. I tried sending messages both to the group and to private messages of the bot.

**Comment by Sreyas-Sreelal** [comment]
I can't reproduce this issue with the code you provided. 

![image](https://user-images.githubusercontent.com/17766494/227436949-885fee77-3984-47fd-8b2b-73e99bac9dd0.png)

![image](https://user-images.githubusercontent.com/17766494/227436976-6e010db7-c177-4a7d-9505-5ad1c6a9b084.png)
![image](https://user-images.githubusercontent.com/17766494/227437041-f911d640-ca41-4919-8096-0eb1241ba563.png)

Could you give me a minimal reproduceable code?  Are you using any other plugins? What are the permissions of the bot? Which platform/OS you using?

**Comment by FelixKot** [comment]
You can go to my chat to check everything: https://t.me/+gehWehOBkiFjZjAy
I'm tested on Windows and Linux
`
#include <tgconnector>

#define CHAT_ID (TGChatId:"-991735423")

new TGBot:g_bot;

//------------------------------------------------------------------------------------------------------------------------------
public OnGameModeInit()
{
	#if defined m_tg_OnGameModeInit
		new i_return = m_tg_OnGameModeInit();
	#endif
	
	g_bot = TGConnect("6158265339:AAGuFkR9v56i39ToxiK4L35EOmSF0E6AqoQ");
	if(g_bot != INVALID_BOT_ID) {
		printf("bot connected successfully!");
	} else {
		printf("Error: bot couldn't connect");
	}
	
	#if defined m_tg_OnGameModeInit
		return i_return;
	#else
		return 1;
	#endif
}
#if defined _ALS_OnGameModeInit
	#undef OnGameModeInit
#else
	#define _ALS_OnGameModeInit
#endif
#define OnGameModeInit m_tg_OnGameModeInit
#if defined m_tg_OnGameModeInit
	forward m_tg_OnGameModeInit();
#endif

public OnTGMessage(TGBot:bot,TGUser:fromid[],TGMessage:messageid) {

	print("yes");
	if(g_bot != bot){
		return 1;
	}

	new
		message[50],
		username[24],
		chatname[56],
		server_msg[128];

	TG_CacheGetMessage(message);
	TG_CacheGetUserName(username);
	TG_CacheGetChatName(chatname);

	format(server_msg,128,"[%s] %s(%s): %s",chatname,username,_:fromid,message);
	print(server_msg);
	SendClientMessageToAll(-1,server_msg);

	return 1;
}


public OnTGUserJoined(TGBot:bot,TGUser:userid[]) {
	new
		TGChatId:chatid[12],
		username[24],
		chatname[56],
		server_msg[128];

	TG_CacheGetUserName(username);
	TG_CacheGetChatID(chatid);
	TG_CacheGetChatName(chatname);

	format(server_msg,128,"User %s(%s) joined %s(%s)",username,_:userid,chatname,_:chatid);
	print(server_msg);
	SendClientMessageToAll(-1,server_msg);
	return 1;
}

public OnTGUserLeft(TGBot:bot,TGUser:userid[]) {
	new
		TGChatId:chatid[12],
		username[24],
		chatname[56],
		server_msg[128];

	TG_CacheGetUserName(username);
	TG_CacheGetChatID(chatid);
	TG_CacheGetChatName(chatname);

	format(server_msg,128,"User %s(%s) left %s(%s)",username,_:userid,chatname,_:chatid);
	print(server_msg);
	SendClientMessageToAll(-1,server_msg);
	return 1;
}

CMD:sendtgmessage(playerid,params[]) {
	TG_SendMessage(g_bot,CHAT_ID,params);
	return 1;
}`
