### ISSUE TITLE
Offer. Add Cyrillic support.

### ISSUE THREAD

**Issue by FelixKot** [Sreyas-Sreelal/tgconnector#9]
I propose to add support for Russian letters. Previously contacted the author, and did not understand whether there will be an update in the near future.
Now I am actively developing based on this api, and this will help me and other users of the Russian-speaking community a lot!
Thank you in advance.

**Comment by MuthaX** [comment]
@FelixKot you can use [PawnUTF](https://github.com/MuthaX/PawnUTF) for conversion between UTF-8 characters and your local codepage characters (CP-1251).
